### ISSUE TITLE
Force trailing slash instead of preserving?

### ISSUE THREAD

**Issue by zachleat** [tweetback/tweetback-canonical#10]
Right now this repo preserves trailing slashes or no trailing slashes given the source URL, for example

```
https://twitter.com/zachleat/status/123

// returns
https://www.zachleat.com/twitter/123
```

```
https://twitter.com/zachleat/status/123/

// returns
https://www.zachleat.com/twitter/123/
```

I wonder if this default should be changed, given that I think URLs from Twitter (exclusively?) leave off the trailing slash.

This causes a problem when redirects are not in place. Just as an example I’ve noticed that @matthewp’s URLs don’t work without trailing slash: https://matthewphillips.info/tweets/1592558080667312130 doesn’t work and is what is currently given back from this package.

A trailing slash needs to be added for it to work: https://matthewphillips.info/tweets/1592558080667312130/

Should we always force a trailing slash? It’s certainly the safest thing for tweetback archive output (but most hosts fix these redirects automatically, see https://www.zachleat.com/web/trailing-slash/)

One other idea here would be to force the convention in https://github.com/tweetback/tweetback-canonical/blob/main/mapping.js. If the source has a trailing slash, force it. If not, leave it off.

**Comment by nhoizey** [comment]
I would vote for forcing the trailing slash.

**Comment by matthewp** [comment]
Mine don't work without because I'm using S3 and CloudFront, neither of which do any sort of index.html routing. The trailing slash only works because I wrote a [CloudFront Function](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cloudfront-functions.html) for that.  I can, and probably will now that I know this problem, fix the non-trailing slash just for this site, but it's not something you get for free using S3 + CloudFront.

**Comment by zachleat** [comment]
Gonna close this for now since @matthewp fixed it upstream! Might revisit if we have other issues!
